.gitignore
src/Classes/Daemons/MyRadio_PlaylistsDaemon.php
src/Classes/ServiceAPI/MyRadio_TracklistItem.php
src/Classes/iTones/iTones_Playlist.php

Playlist generator fixups

---

src/Classes/Config.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/MyRadio/pwChange.php
src/Templates/MyRadio/pwReset.twig

Fix changing passwords on anything that isn't ury

---

src/Classes/ServiceAPI/MyRadio_Track.php

Fixes an issue with precise where it will never return matches if album
is not set.

Don't add album title parameter if there isn't one

---

schema/base.sql
schema/patches/1.sql
src/Classes/Config.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/MyRadio/default.php
src/Controllers/MyRadio/timeslot.php
src/Controllers/Profile/edit.php
src/Templates/MyRadio/getOnAir.twig

Requires adding a 'contract_signed' column to members

Add ability to sign Contract via MyRadio

---

src/Classes/Config.php
src/Classes/ServiceAPI/MyRadio_Swagger.php
src/PublicAPI/index.php

Not the best branch name, whoops.

Access Control and OPTIONS

---

src/Classes/ServiceAPI/MyRadio_Swagger.php
src/Classes/ServiceAPI/MyRadio_Timeslot.php

Fix Mixclouder breakage due to API expecting POST request for setMeta

---

src/Public/js/myury.core.js

Only prompt to send error reports when there's an error.

---

src/Classes/ServiceAPI/MyRadio_Track.php

I think this deals with the clashes. Hopefully good to go now.

Precise search for getSimilar

---

src/Classes/ServiceAPI/MyRadio_Officer.php
src/Classes/ServiceAPI/Profile.php

do - may force an update before object exists?. Needs test.

Fixes #456. Attempt to add cache refreshing. Quite possibly not the correct thing to

---

src/Controllers/Scheduler/editSeason.php

Found looking at the logs. Not actually tested, done based on other usages of the function
Also, if there are any other *minor* fixes needed anywhere, let me know and i'll take a look

Fix season owner check

---

schema/api.json
src/Classes/MyRadio/CoreUtils.php
src/Classes/ServiceAPI/MyRadio_APIKey.php
src/Classes/ServiceAPI/MyRadio_Swagger.php
src/Classes/ServiceAPI/MyRadio_Swagger2.php
src/Controllers/api/v2.php
util/checkpassword

Move checkpassword to apiv2

---

src/Classes/ServiceAPI/MyRadio_APICaller_Common.php

fixes method exception introduced in #486

APICaller_Common getPermissions()

---

src/Classes/Daemons/MyRadio_PlaylistsDaemon.php

Looked at the API. It looks like this is how the table should now be set up. But what do I ever know about this stuff? #codingwhileclueless
As for the Group and Hype stuff - it remains to be seen what Last.fm are going to do with these.

Last.fm API update broke Geo Chart

---

src/Classes/ServiceAPI/MyRadio_Season.php

add information about cancelling a timeslot to the email

update new shows email

---

src/Classes/ServiceAPI/MyRadio_User.php

wrong array keys and data type used

Hotfix set payment

---

src/Classes/Daemons/MyRadio_PlaylistsDaemon.php

It looks fixed. Can we go back to 150?

Revert "It is worse than I thought..."

---

src/Classes/ServiceAPI/MyRadio_Selector.php

correct syntax for default values

---

src/Classes/ServiceAPI/MyRadio_Swagger2.php

hotfix some breakages from #482

Hotfix api methods

---

src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/Profile/view.php
src/Templates/Profile/user.twig

I don't think any api endpoints use 'public_email' and seeing as it isn't the public one it shouldn't have been named that in the first place...

hotfix profile view

---

src/Classes/ServiceAPI/MyRadio_Selector.php
src/Controllers/Scheduler/stop.php
src/Controllers/Timelord/a-update.php

some methods also renamed to get correct API method mapping

make selector static

---

.gitignore
src/Controllers/Scheduler/myShows.php
src/Templates/MyRadio/fullimage.twig
src/Templates/base.twig
src/Templates/parts/table-content.twig

#463 still has raw in error and in news which might need doing too

this should fix up #463

---

composer.json
src/Classes/Config.php
src/Classes/MyRadioException.php

This (MyRadioException) was the easiest thing to start with, not sure if there are any other useful things to hook into

Add Sentry integration

---

src/Classes/ServiceAPI/MyRadio_Track.php

Fixes #321

---

src/Public/js/myury.webcam.tracker.js

Fixes #327

---

src/Public/js/nipsweb.librarypane.js

Fixes #274

---

src/Controllers/Stats/fullTracklist.php

Fixes #325

---

src/Public/js/nipsweb.librarypane.js

Replace the new show/hide JS with the existing. Better than having no
search boxes at all.
**Do not delete branch after merge** -- JS fix to #274 needs reapplying without breakage this time

Hotfix to #536 - will probably result in #274 reappearing

---

src/Classes/Daemons/MyRadio_PlaylistsDaemon.php

At some point I will probably write something to utilise Spotify's API instead of the mostly broken one of Last.fm. In the meantime, this will make the bits that do work work more like they should. Basically, it is a redo of the previous patch as things are still weird with multiples of 10 in the API and Last.fm seem like they will never fix anything (least of all if it is reported).

Last.fm is terrible!!

---

src/Classes/ServiceAPI/MyRadio_Officer.php

Clears Profiles caches when officer stands down

---

src/Classes/Config.php
src/Classes/MyRadio/CoreUtils.php
src/MyRadio_Config.local.php.dist

This should probably be a configurable item, since it seems to change all the time...

Update yusu API endpoint

---

src/Classes/Daemons/MyRadio_BAPSSyncDaemon.php
src/Classes/NIPSWeb/NIPSWeb_BAPSUtils.php
src/Classes/ServiceAPI/MyRadio_Creditable.php
src/Classes/ServiceAPI/MyRadio_User.php

Also consistent API responses.

Fix BAPS Recommended Audio

---

src/Classes/ServiceAPI/MyRadio_User.php

This is what was breaking aliasgen.

Return `receive_email` by default for Member

---

src/Public/css/style.css
src/Templates/base.twig
src/Templates/parts/base_head.twig
src/Templates/parts/nav.twig

Changes this:
to this:
I think this is much nicer :)

Make MyRadio scale quite a bit better when viewed on a mobile device

---

src/Classes/Config.php
src/Classes/MyRadioTwig.php
src/Templates/parts/nav.twig

Not sure if the var name homeurl is descriptive enough?
Closes: #583

Add home page link to nav bar

---

src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/MyRadio/login.php

the results of the following query should be resolved before this is merged:
`SELECT memberid,eduroam FROM member WHERE eduroam != lower(eduroam);`

Make usernames lowercase, and lowercase eduroam username on user creation

---

src/Public/js/sis.selector.js

Closes UniversityRadioYork/Issues#63

Removed open on start feature of the SIS selector.

---

src/Templates/Profile/user.twig

My first pedantic dabble into MyRadio :)

Added a Bio: label to profile

---

src/Menus/menu.json

Fixes: UniversityRadioYork/Issues#82

Changed beds/jingles link.

---

src/Public/js/nipsweb.managelibrary.js

Hopefully sends the explicit tick box on NIPSweb track uploader :)

---

src/Public/css/planner.css
src/Public/js/nipsweb.player.js

Make player position bar stop at the end & fix tooltips!

---

src/Controllers/Webcam/archive.php

Just thought I would make this page actually be a page, y'know.

Made the webcam archive page actually display a page.

---

src/Classes/ServiceAPI/MyRadio_Swagger2.php
src/Classes/ServiceAPI/MyRadio_TracklistItem.php

It's either a single-option call, or an invalid request.

Fix single-option non-static method calls

---

src/Classes/MyRadio/MyRadioFormField.php
src/Classes/ServiceAPI/MyRadio_Track.php
src/Controllers/Library/editTrack.php

This doesn't currently have an easy way to access it, but I'm not sure when I'll be able to finish that and it would probably still be helpful to have now. you can access with editTrack?trackid=XXXX

Edit track form and functionality

---

src/Public/js/sis.messages.js

So it doesn't break :P
Fixes: #634

Make number only messages strings!

---

src/Public/css/style.css

Think this improves things over forcing the width to 90% which makes dropdowns and so on rather wide

Alter the width of items in forms

---

src/Classes/ServiceAPI/MyRadio_Demo.php
src/Classes/ServiceAPI/MyRadio_Track.php
src/Controllers/Scheduler/listDemos.php

Promise I've tested this one
...So much so I found a different bug

Actually fix demos

---

src/Classes/ServiceAPI/MyRadio_Track.php
src/Controllers/Library/editTrack.php

Will need db additions to rec_track.

Edit History for Track Editor + Submit Blank Digitised By.

---

.gitignore
Vagrantfile
composer.json
sample_configs/bootstrap.sh
scripts/bootstrap.sh
scripts/install-tests.sh
src/Classes/Config.php
src/Classes/MyRadio/CoreUtils.php
src/Classes/MyRadioEmail.php
src/Classes/MyRadioException.php
src/Controllers/Setup/checks.php
src/Controllers/Setup/save.php
src/Templates/minimal.twig

Largely stuff taken out of the php-7 branch, but some other stuff (notably the config writing) as well

Fixup vagrant enough for it to work

---

src/Controllers/Scheduler/editShow.php

Set credits memberids, not members

---

src/Classes/ServiceAPI/MyRadio_List.php

Pulled out of @mstratford's show planner prq as it affects several other
things

Fixed missing '$' in MyRadio_List

---

src/Classes/MyRadioTwig.php
src/Classes/ServiceAPI/MyRadio_ChartRelease.php
src/Classes/ServiceAPI/MyRadio_ChartRow.php
src/Classes/ServiceAPI/MyRadio_ChartType.php
src/Classes/ServiceAPI/MyRadio_Quote.php

Also fix a warning about statically calling __wakeup()
Related to #668

Fix MyRadioTwig::addInfo

---

src/Classes/MyRadio/URLUtils.php
src/Controllers/MyRadio/login.php

Stops the 404, and also alerts us to places where this shouldn't be happening 👍

Fixed broken error redirect

---

src/Templates/Scheduler/createSeason.twig

Fixes UniversityRadioYork/Issues#114

Added training quiz link for PC

---

src/Classes/ServiceAPI/MyRadio_TracklistItem.php
src/Controllers/Stats/fullTracklist.php
src/Controllers/Stats/mostListenedShowYear.php
src/Controllers/Stats/mostMessagedShowYear.php
src/Public/js/myradio.stats.fulltracklist.js
src/Public/js/myradio.stats.mostmessagedshow.js
src/Public/js/myradio.stats.mostmessagedtimeslot.js

Added / fixed some incorrect / missing datatables config js files and allowed Manual SIS entered tracks to not break the CSV/fullTracklist output.
Also removed some warnings from the top of the page!

Fix up some of the Stats pages.

---

src/Classes/MyRadioEmail.php

We don't need to email everyone for the number of people in the list. Just the one will do :)

Stop multiple emails!

---

src/Controllers/Website/editBanner.php
src/Templates/Website/bannerfrm.twig

Makes looking for banners much easier :)

Give a little banner preview.

---

schema/base.sql
src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/Profile/bulkAdd.php
src/Controllers/Profile/edit.php
src/Controllers/Profile/quickAdd.php
src/Controllers/Profile/view.php
src/Controllers/Setup/user.php
src/Templates/Profile/user.twig
src/Templates/Setup/user.twig

Requires running `ALTER TABLE member DROP COLUMN sex;` on DB

No sex for MyRadio

---

src/Controllers/Scheduler/editSeason.php

Should probably work out why this didn't generate exception emails
Fixes UniversityRadioYork/Issues#130

season var was undefined when trying to redirect

---

src/Classes/Config.php
src/PublicAPI/index.php

Remove access control

---

src/Classes/ServiceAPI/MyRadio_TracklistItem.php

This is a slight modification to increase variety on jukebox, whilst ensuring that the updated terms of our PPL license are adhered to.

Variety Up & Meeting PPL

---

src/Classes/ServiceAPI/MyRadio_TracklistItem.php

Changed the "===" to match the getAlbum format above, as the getArtist check was still not working. Not that I know much about how anything works, but maybe this will fix it?

$t->getArtist() == $track->getArtist()

---

src/Menus/menu.json

A request to add a couple of links to the "I want to..." section of myradio. 
- Studio 2 Booking
- Event Request Form
I am unsure how to build myradio locally to test, so any input would be great :)

Add a couple of useful documents to myradio.

---

src/Classes/MyRadio/MyRadioForm.php
src/Classes/ServiceAPI/MyRadio_Demo.php
src/Classes/ServiceAPI/MyRadio_Scheduler.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Controllers/Scheduler/allocate.php
src/Controllers/Scheduler/default.php
src/Controllers/Scheduler/listSeasons.php
src/Controllers/Scheduler/listTerms.php
src/Controllers/Scheduler/listTimeslots.php
src/Controllers/Scheduler/myShows.php
src/Controllers/Scheduler/shows.php
src/Menus/Scheduler.json
src/Templates/stripe.twig

Working towards a better scheduler with less (ideally no) ambiguities with changing timezones and less relativity towards term weeks, also allowing more flexibility for scheduling outside of term.

Making a "Better Scheduler"

---

src/Classes/MyRadio/CoreUtils.php
src/Classes/ServiceAPI/MyRadio_Track.php
src/Controllers/Library/editTrack.php
src/Public/css/planner.css
src/Public/js/nipsweb.managelibrary.js

Fixes #717 
Works towards #710

Fix DigitisedBy on Edit Track form and Uploader fixes.

---

src/Classes/ServiceAPI/MyRadio_Timeslot.php

Tested on myradio dev (and 2016-site)

Get multiple results from previousTimeslots.

---

src/Classes/ServiceAPI/MyRadio_Selector.php
src/Classes/ServiceAPI/MyRadio_Webcam.php
src/Controllers/SIS/selector.set.php
src/Public/css/sis.css
src/Public/js/sis.selector.js
src/Public/js/sis.webcam.js

New Features:
- Ability to switch to off air source (with "are you sure" confirmation).
Fixes:
- Hall & Office webcams now actually selectable.
- More consistent naming between sources and webcams. (Outside vs OB etc).
Tested on MyRadio dev with all webcams now selectable (during a scheduled show).
Selector tested switching from Studio 1 to Jukebox to Off Air.

Migrate Webcams / Selector in SIS to Off Air Source

---

schema/base.sql

Already live, so that we have the nice new fancy team pages! (Yes, I forgot about this one)

Team descriptions need more length.

---

src/Classes/ServiceAPI/MyRadio_Show.php

Utterly untested, but the SQL works in phppgadmin...

Add cheap getAllTimeslots function to MyRadio_Show

---

src/Classes/iTones/iTones_TrackRequest.php
src/Controllers/Setup/checks.php

Fixes UniversityRadioYork/Issues#123

Only allow jukebox requests to be made if clean.

---

composer.json
src/Controllers/Setup/checks.php

Hopefully shut travis up
Also arbitrary composer version bump

Codestyle fixes

---

src/Controllers/Mail/archive.php

Because computing don't need an email every so often for this.

Change email archives permissions error.

---

Vagrantfile
scripts/bootstrap.sh

Vagrant config needed jumping up again. Now more closely matches production again :)

Upgrade vagrant to 18.04/Postgresql 10

---

src/Public/js/myradio.form.js

there are other xss issues in this file that I am going through and fixing, but if you want to fix the most immediate one then heres a pr

Modify member typeahead to prevent xss

---

src/Public/js/myradio.form.js

Have not fully tested this yet

Fix the rest of the potention xss issues in typeahead

---

src/Classes/ServiceAPI/MyRadio_Season.php

Lowers the number of emails Computing gets for common user mistakes.

Make a few scheduler errors less critical.

---

.travis.yml
scripts/bootstrap.sh
src/Classes/Config.php
src/Classes/MyRadio/CoreUtils.php
src/Classes/MyRadioEmail.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Classes/ServiceAPI/MyRadio_TrackCorrection.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/Errors/400.php
src/Controllers/Scheduler/cancelEpisode.php
src/Controllers/Setup/strings.php
src/Templates/base.twig
src/Templates/joyrides/first_show.twig

As per usual, completely untested and needs properly reviewing & testing

I wanted to fix some issues

---

src/Classes/ServiceAPI/MyRadio_Podcast.php

While testing discovered that my last changes didn't work, this might fix it.

Trying to fix podcasting getAll SQL

---

src/Classes/ServiceAPI/MyRadio_Podcast.php

Broke everything

---

src/Classes/ServiceAPI/MyRadio_Show.php

Fix broken show image uploaded

---

.eslintignore
.travis.yml
Vagrantfile
composer.json
scripts/bootstrap.sh
src/Classes/ServiceAPI/MyRadio_Track.php
src/Classes/iTones/iTones_PlaylistAvailability.php
src/Public/js/myradio.core.js
src/Public/js/myradio.schedule.view.js
src/Public/js/nipsweb.channelconfig.js
src/Public/js/nipsweb.player.js
src/Public/js/sis.js
src/Public/js/sis.webcam.js

Also fixes the fact MyRadio can't configure it's own config file on Setup.
It also reloads apache2 on vagrant up, it seems to not load the config correctly otherwise.

Upgrade Vagrant to Ubuntu 19.04 / psql11

---

src/Menus/menu.json
src/Templates/MyRadio/getOnAir.twig

Added advanced studio training, uploader training and comments

Main Menu Changes

---

src/Public/js/myradio.webcam.tracker.js
src/Templates/Webcam/focus.twig
src/Templates/Webcam/grid.twig

Show message if no webcams setup.

---

src/Classes/MyRadio/CoreUtils.php

Shows on https://ury.org.uk/myradio/Library/search/ after searching.

Fix Non well formed numerical value error.

---

src/Menus/menu.json

Reverts UniversityRadioYork/MyRadio#799

Revert "Removed quotes board temporary"

---

src/Classes/Config.php
src/Controllers/Errors/Maintenance.php
src/Controllers/root_web.php
src/Views/Errors/Maintenance.php

A prelude to #805 when we might need to shut down show editing to do data backfill.
~~DO NOT MERGE YET, still to be tested~~ **EDIT: probably ready for merge now, tested on -dev**

Allow bringing features down for maintenance

---

src/Classes/Config.php
src/Templates/Mail/emailtemplate.twig

See https://github.com/UniversityRadioYork/2016-site/pull/189

Change the MyRadio default image URL.

---

src/Templates/Webcam/focus.twig
src/Templates/Webcam/grid.twig

People wanted more webcam FPS. Here it is.

Double the webcam framerate, woah.

---

src/Templates/MyRadio/getOnAir.twig

The training status is "manual uploader", consistency is nice.

Change "get music upload trained" to "manual upload"

---

src/Classes/MyRadioTwig.php
src/Public/css/style.css
src/Templates/base.twig
src/Templates/parts/nav.twig
src/Templates/stripe.twig

Need to make MyRadio^2 work nice.

Add "nonav" URL parameter

---

src/Classes/ServiceAPI/MyRadio_Swagger2.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/root.php
src/PublicAPI/index.php

I will be entirely honest, I have no idea why this works, but it works.

Bodge the fucking API into submission

---

src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Public/js/myradio.scheduler.timeslotlist.js

Add metadata for custom mixclouder upload start/end times.

Add mixcloud start/end custom times to timeslot.

---

schema/base.sql
src/Classes/MyRadio/MyRadioSession.php

Make SQL deal with the race condition of multiple simultaneous new session creations.

Fix sso_session duplications.

---

src/Classes/ServiceAPI/MyRadio_Selector.php
src/Public/css/sis.css
src/Public/js/sis.selector.js

~~Ready for review but don't merge yet, as https://github.com/UniversityRadioYork/selectorlistener/pull/5 hasn't gone in yet~~

Add WebStudio as a source in SIS

---

schema/api.json
schema/data-auth.json
src/Classes/NIPSWeb/NIPSWeb_ManagedUserPlaylist.php
src/Controllers/NIPSWeb/default.php
src/Controllers/NIPSWeb/live.php
src/Controllers/NIPSWeb/manage_library.php

Also requires adding records into myury tables for giving people access to the getAllManagedUserPlaylists and getAllManagedPlaylists endpoints.

Bring NIPSWeb into the API for WebStudio.

---

Vagrantfile

If this isn't added then it doesn't work

Update Ubuntu version

---

composer.json
src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/MyRadio_Selector.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Classes/ServiceAPI/MyRadio_TracklistItem.php
src/Controllers/NIPSWeb/load_aux_lib.php

See also https://github.com/UniversityRadioYork/myradio-go/pull/51 and https://github.com/UniversityRadioYork/2016-site/pull/237.
TODO for MVP:

Add podcast RSS feeds

---

schema/base.sql
src/Classes/ServiceAPI/MyRadio_ShowSubtype.php

First part of more usage of subtypes

---

src/Classes/ServiceAPI/MyRadio_Show.php

Fix format differences of cached vs un-cached shows.

---

src/Controllers/Setup/user.php
src/Templates/Setup/user.twig

Gives a password check to the setup and cleans up the display a little

Cs minor alterations 20 04 25

---

src/Controllers/MyRadio/default.php
src/Menus/menu.json
src/Templates/MyRadio/getOnAir.twig
src/Templates/MyRadio/menu.twig

Update links to forms

---

src/Menus/menu.json

added slack to menu

---

README.md

Explains things so Matt doesn't have to!

Super Quickstart Notes

---

schema/api.graphql
src/Classes/ServiceAPI/MyRadio_User.php

Tested on Staging. Compare https://ury.org.uk/api-staging/graphql?query={me{shows{title}}}&debug=true and https://ury.org.uk/api-staging/graphql?query={me{shows(current_term_only:true){title}}}&debug=true

Allow filtering a member's shows by term

---

src/Classes/ServiceAPI/MyRadio_Scheduler.php

Stop Scheduler::findShowByTitle returning duplicates

---

src/Classes/Config.php
src/Classes/ServiceAPI/MyRadio_Officer.php

Specifically, when they get one that they've never had before.
Resolves #838.

Email people when they get a new officership

---

schema/api.graphql
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Controllers/api/graphql.php

Because getCurrentAndNext is a pain in the arse to work with

Add getCurrentAndNextObjects and expose it to GraphQL

---

src/Classes/ServiceAPI/MyRadio_Track.php

seems like a decent thing to do

set last_updated on upload

---

README.md
src/Controllers/Setup/dbschema.php
src/Controllers/Setup/dbserver.php

I have added a full step by step guide (with error correction) to installing myradio in the README file. While doing this there was an error that appeared after database credentials were added, requiring a slight change to dbschema.php (thanks stratford)

Fix the install process and give clear instructions

---

src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/root_web.php

duration for how long someone is _theoretically_ on radio, can be used in https://github.com/UniversityRadioYork/2016-site/issues/53

implement radio time

---

schema/api.graphql
src/Classes/ServiceAPI/MyRadio_Track.php
src/Classes/ServiceAPI/MyRadio_TracklistItem.php

Possible since the Jukebox change I rolled out earlier today.

Add MyRadio_TracklistItem::getNowPlaying

---

schema/api.graphql
schema/api.json
schema/base.sql
src/Classes/NIPSWeb/NIPSWeb_TimeslotItem.php
src/Classes/ServiceAPI/MyRadio_Track.php
src/Classes/ServiceAPI/MyRadio_TracklistItem.php
src/Controllers/Library/editTrack.php
src/Public/js/myradio.library.findMissing.js
src/Public/js/myradio.library.search.js

Tested on staging (with DB changes already applied).

Add Outro and Cue Support (For WebStudio)

---

schema/patches/7.sql
src/Classes/ServiceAPI/MyRadio_Scheduler.php
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Controllers/MyRadio/a-timeslotSignin.php
src/Controllers/MyRadio/timeslot.php
src/Public/js/myradio.timeslot.js
src/Templates/MyRadio/timeslot.twig

* Sign-ins now have a location
* Guests can be signed in (with a freeform text box)
Next step will be to make a UI for getting at the data, but this is a good enough start for a review.

Sign-in changes for contact tracing

---

src/Classes/ServiceAPI/MyRadio_Track.php

fix matt strat

---

src/Classes/ServiceAPI/MyRadio_Track.php

fix strat 2

---

src/Classes/ServiceAPI/MyRadio_Track.php

fix my oops

---

src/Classes/ServiceAPI/MyRadio_Track.php

1, 2, 3, 4, 5, 6, 7, 8, 9, 10..what happens now??

I can't count

---

schema/data-actionsauth.json
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Controllers/Scheduler/tracking.php
src/Menus/menu.json
src/Public/js/myradio.scheduler.tracking.js

Not the best way of implementing, but definitely the simplest. Not on any menus, cause in true MyRadio fashion, We ❤️️ Hidden Links (/Scheduler/tracking)

Sign In Details

---

src/Public/js/myradio.core.js
src/Public/js/nipsweb.import.js
src/Public/js/nipsweb.init.js
src/Templates/NIPSWeb/import.twig

Allows it to work with WebStudio with no URL query string param hacks.

Make Show Plan Importer 100% API based.

---

src/Public/js/myradio.stats.jukeboxplaycounter.js

I missed a table from not showing the outro field.

---

schema/api.json

marks is going to complain that i haven't graphqlanised it

expose nipsweb item

---

src/Public/js/nipsweb.import.js

Importer wouldn't import properly if the show plan didn't have at least something in all three channels.

Don't trust API to return 3 channel if they're empty.

---

src/Templates/NIPSWeb/main.twig

res-filter-artist-container makes me suspicious this might break the style of something. I wouldn't imagine it would take more than this to fix the order though.

Move "filter by track" above artist

---

src/Controllers/Webcam/focus.php
src/Public/css/myradio.webcamfocus.css
src/Templates/Webcam/focus.twig

Previously this page appeared incomplete. Now allows user to select which view they wish to focus on.

Can now select which camera to watch in focus mode

---

src/Classes/ServiceAPI/MyRadio_APICaller_Common.php

MyRadio_APICaller::canCall has a superuser check, but hasAuth doesn't have a corresponding one, which causes... issues...

Make MyRadio_APICaller::hasAuth return true if we're sudo

---

src/Classes/ServiceAPI/MyRadio_User.php

Also don't hardcode IDs in the code because that's silly

Make WebStudio training count as "studio demoed"

---

composer.json
src/Classes/Config.php
src/Classes/MyRadioGeoIP.php
src/Classes/SIS/SIS_Utils.php
src/Controllers/Setup/checks.php

Make SIS use GeoIP 2

---

src/Classes/MyRadioEmail.php
src/Classes/ServiceAPI/MyRadio_Track.php

Add "reportExplicit" endpoint

---

src/Classes/Daemons/MyRadio_PlaylistsDaemon.php
src/Classes/iTones/iTones_Playlist.php

We can't pass in MyRadio_Track objects via the API, so let it accept IDs.

Make setTracks work via the API

---

src/Classes/ServiceAPI/MyRadio_Timeslot.php

will this make the cachinator happy? probably not, cause its the cachinator.

cache mccache face

---

src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Controllers/Scheduler/editSeason.php
src/Controllers/Setup/checks.php

oh...and a small issue in the setup. but mainly metadata fun

editing seasons

---

src/Classes/iTones/iTones_Playlist.php

Digitised Tracks in Playlist

---

schema/data-actions.json
schema/data-actionsauth.json
src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Controllers/Podcast/suspendPodcast.php
src/Public/js/myradio.podcasts.js

suspending/unsuspending mainly.
- people can suspend a podcast
- people can request to unsuspend a podcast with a reason

some podcast stuff

---

src/Controllers/MyRadio/addNews.php

feeds latest news feed into new news feed. make updating PIS easy

Imagine being able to edit news feeds, not just copying the old one ;)

---

src/Classes/ServiceAPI/MyRadio_Selector.php

oh look... i put a double dash in the branch name. Basically, if we only have a feed on OB2, it'll consider the source powered off, when it isn't. This should fix that, but I haven't tested, I don't have much internet to play with atm, and I'm using it to write the PR ;)

Fix OB2 Power

---

src/Templates/MyRadio/menu.twig

add the open in new tab icon fo external links (I think)

Add new tab icon

---

src/Templates/joyrides/first_show.twig

(this hasn't been updated in long time)

First Show Joyriding Update

---

schema/api.graphql

Fix GraphQL Types

---

src/Classes/Daemons/MyRadio_ExplicitDaemon.php

Slow explicit daemon down so we can rerun big batches without being rate limited by itunes

Slow Down for Rate Limiting

---

src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Controllers/Podcast/editPodcast.php
src/Public/js/myradio.podcasts.js

Podcast Photos

---

schema/base.sql
src/Classes/ServiceAPI/MyRadio_Quote.php
src/Controllers/Quotes/editQuote.php
src/Controllers/Quotes/randomQuote.php
src/Menus/Quotes.json
src/Menus/menu.json
src/Public/js/myradio.quotes.js
src/Templates/Quotes/default.twig

Revert "rip quotes board ????-2020"

---

src/Controllers/MyRadio/timeslot.php
src/Public/js/myradio.timeslot.js

this only half fixes Michaels issue, sorry Michael

Add Please Select location

---

src/Classes/Config.php
src/Classes/Daemons/MyRadio_TrackAndTraceDaemon.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Controllers/Scheduler/tracking.php
src/MyRadio_Config.local.php.dist
src/Public/js/myradio.scheduler.tracking.js

I still need to test the daemon, among other things

Summer Term Track and Trace

---

src/Classes/ServiceAPI/MyRadio_TracklistItem.php

See #1005 for original approval of this cherry-picked commit.

Prevent BAPS from tracklisting to timeslot when off air.

---

src/Classes/ServiceAPI/MyRadio_Podcast.php

Will this actually work? Who knows?

Create podcasts atomically

---

src/Classes/ServiceAPI/MyRadio_Show.php

Apple's complaining about it (or the lack thereof).

Add copyright tag to podcast RSS

---

src/Classes/ServiceAPI/MyRadio_Podcast.php

I swear, if the problem was that we just didn't call updateCacheObject, I will...

Attempt to fix podcast caching, yet again

---

src/Menus/menu.json

Removes event & visualisation, reorders some, and renames some to be more appropriate

Remove unused google forms

---

src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/MyRadio_Swagger2.php

The API thinks a MyRadio_User param is an int. It is not.

MyRadio_Podcast::getPodgetPodcastsAttachedToUser: fix API

---

src/Templates/MyRadio/getOnAir.twig

Add in the open new page icon for buying a membership, as it opens to YUSU

Add in the open new page icon

---

src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/MyRadio_Swagger2.php

The mixin nonsense made some APIs really unhappy. Reverting until I've figured out what's gone wrong.
Reverts UniversityRadioYork/MyRadio#1015

Revert "MyRadio_Podcast::getPodgetPodcastsAttachedToUser: fix API"

---

schema/api.json
schema/data-auth.json
schema/patches/10.sql
src/Classes/ServiceAPI/MyRadio_ShortURL.php
src/Controllers/Website/editShortUrl.php
src/Controllers/Website/shortUrls.php
src/Menus/Website.json
src/Public/js/myradio.website.shorturllist.js
src/Templates/Website/shortUrls.twig

Goes in tandem with https://github.com/UniversityRadioYork/2016-site/pull/297

Short URLs

---

src/Menus/menu.json

Added the google form for off-air studio booking and move the slack link from info to get on air

Add new off air studio booking form and move slack

---

src/Templates/MyRadio/getOnAir.twig

its safe to say, if your're studio trained you're studio proficient

change demoed (studio proficient or ws trained) to studio trained

---

src/Templates/NIPSWeb/manage_library_manual.twig

Uploader doesn't like window's zip preview.

Add unzip notice to uploader.

---

src/Classes/Config.php
src/Classes/MyRadio/MyRadioLDAPAuthenticator.php

Looking for someone without chance of any of the other authenticators to login to test it.

Add regex support for LDAP to block fake logins.

---

src/Controllers/Scheduler/autoViz.php

Make the enable disable feature more clear in its feature and function

Update enable disable message on autoViz table

---

composer.json
schema/patches/14.sql
schema/patches/9.sql
src/Classes/ServiceAPI/MyRadio_Event.php
src/Controllers/Events/addToCalendar.php
src/Controllers/Events/iCal.php
src/Controllers/root.php
src/Menus/Events.json
src/Templates/Events/addToCalendar.twig

I've tested it, and it works, except that google calendar refuses to import them for some reason. KOrganizer handles it fine so I guess Google makes good software.

Export events calendar to iCal

---

src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Controllers/Events/iCal.php

Include shows in user iCal feed

---

composer.json
src/Classes/MyRadio/MyRadioForm.php
src/Classes/ServiceAPI/MyRadio_Event.php
src/Controllers/Events/duplicateEvent.php
src/Templates/Events/viewEvent.twig

Replaces the recurring events feature (which was never fully implemented) with a button to duplicate a given event.

Event duplication

---

src/Controllers/Training/createDemo.php

```
Notice : Undefined index: demo_id - In /usr/local/www/myradio/src/Controllers/Training/createDemo.php on line 29
```

Fix PHP notice on createDemo page

---

src/Classes/ServiceAPI/MyRadio_Demo.php

Update signup cutoff and max participants when editing demo

---

src/Classes/ServiceAPI/MyRadio_Podcast.php

Remove notice about clearing cache from podcast form

---

schema/data-auth.json
src/Classes/MyRadioEmail.php
src/Classes/ServiceAPI/MyRadio_Demo.php
src/Classes/ServiceAPI/ServiceAPI.php
src/Controllers/Training/cancelDemo.php
src/Controllers/Training/listDemos.php
src/Public/js/myradio.training.demolist.js

Cancel demos

---

src/Classes/Config.php
src/Classes/Daemons/MyRadio_DemoCleanupDaemon.php

Clean up demo_attendee records for missed demos

---

src/Classes/ServiceAPI/MyRadio_Show.php

Wrap setShowPhoto in a transaction

---

schema/patches/16.sql
schema/patches/17.sql
src/Classes/ServiceAPI/MyRadio_Scheduler.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Classes/ServiceAPI/MyRadio_Term.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/Scheduler/allocate.php
src/Controllers/Scheduler/editSeason.php
src/Controllers/Scheduler/editTerm.php
src/Controllers/Scheduler/listTerms.php
src/Public/css/style.css
src/Public/js/myradio.scheduler.termlist.js
src/Templates/Scheduler/createSeason.twig

changed the scheduler to accommodate terms of varied lengths and have names related to dates not week numbers because semesters have stupid week names and also this is better anyway

Jp semester 2

---

src/Menus/menu.json

I added a link to the song requests page

song requests link

---

src/Menus/menu.json

"Request Songs" menu item was duplicated, duplicate has been removed

Removed duplicate item in menu.json

---

src/Classes/ServiceAPI/MyRadio_Scheduler.php

updates 10 week limit for the scheduler for 11 weeks 
To work for semesters which are 11 weeks
https://www.york.ac.uk/students/studying/semesters/#:~:text=You%20will%20be%20expected%20to,whilst%20you%20are%20undertaking%20assessments.
Nya :3
- Ren

Update MyRadio_Scheduler.php - Fixes the 10 week limit for semesters

---

src/Menus/menu.json

Add another item to I want to.. section
This allows anyone on my radio to have a link to google form to request key card access for our new key card system.

update menu.json with keycard form

---

src/Classes/MyRadio/MyRadioSession.php
src/Classes/ServiceAPI/MyRadio_Banner.php
src/Classes/ServiceAPI/MyRadio_UserTrainingStatus.php

Fixed the breaking issue (the wild MyRadio_Photo*) and _some_ of the warnings (I can't be bothered to find all of them tbh). So, if you merge this, you'll get a load of warnings on MyRadio, but hey, at least it'll be up to date :)
*ok, yeah, I just removed that annotation, maybe it was trying to say it is fundamentally wrong, but I'm not gonna check that :)

fix the breaking issue in php8 and some of the warnings

---

src/Templates/Scheduler/stop.twig

London Bridge has fallen

---

src/Classes/MyRadio/MyRadioNews.php
src/Classes/ServiceAPI/Profile.php

Hi following the addition nickname, I didn't catch that adding the column nickname break search feature on member and news. I am reverting this for now so search isn't broken on master.

didn't catch these break search. I will remove them for now

---

src/Classes/MyRadio/MyRadioNews.php
src/Classes/ServiceAPI/Profile.php
src/Public/js/myradio.newslist.js
src/Public/js/myradio.profile.list.js
src/Templates/MyRadio/getOnAir.twig

The fix was add them to twig.js Silly me

Readding nicknames in members and news list. After fixing search being deleted 

---

composer.json
src/Classes/MyRadio/GraphQLUtils.php

Updates php-graphql (not necessary for the fix, but still good to have)
Fixes the TypeError on graphql queries

Fix graphql api

---

src/Classes/ServiceAPI/MyRadio_User.php

The get involved page is currently broken by this.

fix: do not require nickname on signup

---

docs/install.md
schema/api.graphql
schema/api.json
schema/base.sql
schema/patches/19.sql
scripts/gdprdeleteuser.php
src/Classes/MyRadio/MyRadioNews.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Track.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Classes/ServiceAPI/Profile.php
src/Controllers/Profile/bulkAdd.php
src/Controllers/Profile/edit.php
src/Controllers/Profile/quickAdd.php
src/Controllers/Setup/user.php
src/Controllers/root.php
src/Public/js/myradio.form.js
src/Public/js/myradio.newslist.js
src/Public/js/myradio.profile.list.js
src/Public/js/myradio.timeslot.js
src/Templates/MyRadio/getOnAir.twig
src/Templates/Profile/user.twig
src/Templates/Setup/user.twig
tests/api/ShowSpecCest.php

It has caused many issues due to not being fully tested, and we need MyRadio to be completely functional for freshers.

Revert nicknames until tested further

---

Dockerfile.prod

Corrects the ordering of arguments to `ln`

Fix prod dockerfile

---

src/Menus/menu.json

Solves part of issue https://github.com/UniversityRadioYork/MyRadio/issues/1184

Add clipper to Show Tools list under logger

---

src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/MyRadio_Show.php

search can now take the search query as a query paramter, enabling search for special characters

improve search

---

src/Classes/ServiceAPI/MyRadio_Show.php

include @ in email string

---

src/Classes/MyRadio/MyRadioNews.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Controllers/Scheduler/addEpisode.php
src/Public/js/myradio.scheduler.pending.js
src/Public/js/myradio.scheduler.seasonlist.js
src/Public/js/myradio.scheduler.timeslotlist.js
src/Public/js/myradio.stats.mostlistenedtimeslot.js
src/Public/js/myradio.stats.mostmessagedtimeslot.js

Few scheduler changes here.
To help with testing this branch has been deployed on staging at [https://ury.org.uk/myradio-staging](https://ury.org.uk/myradio-staging)
- New add episode button on season items.
- Implement a move button on episodes (replaces having to edit URL manually).
- Users now receive an email when shows are moved. (Note that these wont send on staging but just check nothing breaks? we'll test in prod)

Colin scheduler changes dev

---

src/Classes/ServiceAPI/MyRadio_Timeslot.php

Update move episode email subject line

---

src/Classes/ServiceAPI/MyRadio_Demo.php

just calls addAttendee correctly (i don't know php)
before fix: unknown function error
after fix: signing up to demos works

fix: attending demos though UI
