schema/base.sql
src/Classes/APCProvider.php
src/Classes/Database.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Classes/ServiceAPI/ServiceAPI.php
src/Interfaces/CacheProvider.php

Substantially improves startup time and database load for fetching all shows on an empty cache. Provides the ServiceAPI functionality to expand this further in future.
- Update image_metadata type to TEXT
- Deprecate Database::decodeArray
- Add default factory method to serviceapi
- Re-write show select query to support returning multiple rows
- Replace getAllShows iterator with single query
- Expand CacheProvider interface with getAll feature

Add factories for show

---

src/Classes/ServiceAPI/MyRadio_List.php
src/Classes/ServiceAPI/MyRadio_Swagger2.php

Some things, such as /api/v2/list/22/members, returns a set of dataSource'd objects from another class. Mixins are passed through correctly, but permissions were not properly verified.
This fixes that.

Support datasource responses with mixins

---

src/Classes/Database.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Classes/ServiceAPI/ServiceAPI.php

- Get rid of ?dbdbg. It was a hack, could actually cause issues if caching was off (would break MyRadio entirely), and the new DB_PROFILE constant means that things can be investigated on the CLI.
- Lazy load some attributes of Timeslots and Users. This should improve perfomance on a cold cache. Disabled caches are still awful in toDataSource scenarios due to getMeta's performance.
- Made cache updates lazy and not apply until destruct time, so multiple edits don't get written at once.

Some performance optimisations

---

src/Classes/Daemons/MyRadio_PlaylistsDaemon.php

Like Heart, but actually more music variety. Last.fm has a bug in their API still, which is resulting in weird results for the Worldwide Top Chart. Upping the limit a small amount will fix this, and give a little more variety in the playlists. Groups still not working, so if those are looking like they will never come back we can think about ditching those.

Workaround for limit=X00 bug = more music variety.

---

src/Classes/ServiceAPI/MyRadio_User.php

I'm not actually sure why activateMemberThisYear exists... Maybe it would be useful as a permission block if it didn't take in the payment amount as a variable.

lazy loading of payments fix

---

src/Classes/APCProvider.php
src/Classes/MemcachedProvider.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Interfaces/CacheProvider.php

should fix the problems with getAllKeys() which is a fairly useless function:
"This is not an atomic operation, so it isn't a truly consistent snapshot of the keys at point in time. As memcache doesn't guarantee to return all keys you also cannot assume that all keys have been returned."
Every so often it would just return false when keys existed.
With this we keep a list of keys to be fetched then fetch them.

getAll() with keys

---

src/Classes/ServiceAPI/MyRadio_Show.php
src/Public/js/myradio.scheduler.timeslotlist.js
src/Public/js/myury.scheduler.pending.js
src/Public/js/myury.scheduler.seasonlist.js
src/Public/js/myury.scheduler.showlist.js
src/Public/js/myury.stats.mostlistenedtimeslot.js
src/Public/js/myury.stats.mostmessagedtimeslot.js

This may have ramifications for things that request shows - potentially mixclouder. However everything apart from 'searchMeta' should have already been receiving arrays

change show credits to array and remove deprecated $full

---

src/Classes/ServiceAPI/MyRadio_User.php

Currently you can't view/work on shows that are in the future, this is a problem if you need to plan a future show block

unrestrict future shows

---

src/Classes/ServiceAPI/MyRadio_Creditable.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Controllers/MyRadio/timeslot.php

This also prevents access to non credited timeslots within a show, though they will still be visible in the list.

check timeslot permissions for the timeslot, making owners generic

---

src/Classes/ServiceAPI/MyRadio_Demo.php
src/Controllers/Scheduler/leaveDemo.php
src/Controllers/Scheduler/listDemos.php

Add ability to leave demos.
This involved reshuffling some logic from MyRadio_Demo to the controller, so that the link could change from join to leave as appropriate. Bonus - no join link is shown if the demo is full.
Resolves #503.

Add ability to leave demos

---

README.md
schema/data-apiauth.json
src/Classes/Config.php
src/Classes/ServiceAPI/MyRadio_Scheduler.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Menus/Scheduler.json
src/Templates/Scheduler/allocate.twig

- Update readme as a hint for the steps needed to make a show (which is really needed to do anything with a new MyRadio)
- Add some missing default API permission entries, without which various bits of MyRadio just error at you
- Fix the allocate season page by using the new location of a user's name and adding back the type_name field for credit dataSource objects
- Add missing Manage Terms link to the Scheduler menu
- Default to using prettier URLs for prettyness

A few bug fixes and niceties I found trying to setup a local MyRadio

---

src/Classes/ServiceAPI/MyRadio_User.php
src/Public/js/myradio.form.js

Fixes: UniversityRadioYork/Issues#56, #592 
Looks like the issues I was having before was due to caching, the code is working as it should now (after ignoring it for ages). It chooses eduroam first, followed by localAlias, followed by memberID as least preferred.  👍

Show eduroam/local_alias/memberID in members drop-downs.

---

src/Classes/ServiceAPI/MyRadio_Swagger.php
src/Classes/ServiceAPI/MyRadio_Swagger2.php
src/Classes/ServiceAPI/MyRadio_Track.php

* Fix only one parameter having a type documented in the API.
* Fix putting single-parameter parameters into the path if they're arrays.
* Add a MyRadio_Track search method that can be used over the API.
* Fix findByOptions, because it turns out it's been broken since we moved the SQL out of the MyRadio_Track constructor and into getInstance.
* Tell Swagger not to expose findByOptions because its signature doesn't make sense for the API.
* Suck at splitting this into multiple commits

Add a track search API call

---

sample_configs/bootstrap.sh
src/Public/css/planner.css
src/Public/js/nipsweb.channelconfig.js
src/Public/js/nipsweb.librarypane.js
src/Public/js/nipsweb.player.js
src/Templates/NIPSWeb/main.twig

I should probably add a description for this one!
This PR (along with a couple small Vagrant fixes), makes uses of the draft Audio Output Devices API, which has been available in Chrome for about a year now.
It enables you to configure a HTMLMediaElement's hardware output device, although with the caveat that the journey in for requesting access in the browser actually asks if you want to grant Microphone access, as the permission for Input/Output is the same.
By clicking on the channel name (e.g. "Channel 1") at the bottom of a channel, a new Channel Settings dialog appears, which currently only has this one new setting.
When this dialog is first opened, Chrome will ask the user for access to the microphone, and if granted the dropdown box shows an enumeration of available hardware …

Add the ability to set the output device, just like a real BAPS.

---

src/Classes/ServiceAPI/MyRadio_Track.php
src/Controllers/Library/addTrack.php
src/Controllers/NIPSWeb/confirm_central_upload.php
src/Public/css/planner.css
src/Public/js/nipsweb.managelibrary.js
src/Templates/NIPSWeb/manage_library_manual.twig

Fixes: #613 
**New features added**
- Nice bootstrap styling everywhere.
- Uploading to Central Music Library now auto-fills from ID3 tags, including if track has "Explicit" in title.
**Fixes**
- Bitrate/Stereo Errors when uploading are now displayed when not uploading to the central music library.
- When uploading to the Central Music Library, if a track fails the bitrate or stereo test, the user can no longer still submit the track to the library.
- For the time being (until get round to making multi-uploads work properly), only one Central Library Track can be uploaded and submitted at a time. Once a track is submitted, another can be uploaded. If a new track is uploaded before one is submitted, the old track will be shown as not submitted, instead of the blue alert box being left on …

Remove LastFm, implement auto ID3 tagging and improve UI of Track Uploader.

---

src/Classes/ServiceAPI/MyRadio_Track.php

Fixes #621 
May not be efficient, but it got rid of the notices 👍  It just makes doubly sure that the values are set before the SQL query 👍 You'll want to merge this before updating MyRadio live.

Fixes non-defined input notices in MyRadio_Track::findByOptions.

---

src/Classes/ServiceAPI/MyRadio_Swagger2.php

As part of refactoring some of the API logic, the explicit method route rules were refactored, and testCredentials was missed out.
This adds it back again.

Fixes the Search API branch removing an API route

---

src/Public/js/nipsweb.player.js

Math.Max does not exist, but Math.max does. Fixes seeking in Show Planner.

Fix Math.Max

---

src/Public/js/nipsweb.player.js

Turns out hesitation was the key to breaking show planner.
If we decided that no change was actually made (we dragged to/from the same place), we didn't dequeue, preventing the next change from being sent off.

Stop Show Planner from forgetting to save changes.

---

src/Classes/ServiceAPI/MyRadio_Timeslot.php

This fixes timelord with one show now returning still as an array.

Only force API to non-array next shows if n=1.

---

schema/base.sql

It's not perfect, but is much better, I think.
Brief incomplete summary:
* Little bit of function reformatting
* Removed a bit of public rapier schema
* Removed site_package/sitetree schemas - appears to have been a precursor to metadata?
* Added some missing constraints
* Deleted/Moved sis_* tables to sis2 schema and renamed appropriately. Have also done this on live db

Resync schema.sql with what's currently live

---

src/Controllers/api/v2.php

This currently ends up entering the logic for three-block paths, when there's only two blocks.

Ignore trailing slashes, as a blank method is technically a valid method

---

src/Classes/ServiceAPI/MyRadio_Track.php
src/Public/js/myradio.form.js

To fix problems with play listing where less useful (most likely ordered by oldest (lowest trackid) first) results caused the required track to be not selectable.

Find tracks better in bloodhound menus

---

src/Classes/Database.php
src/Classes/ServiceAPI/MyRadio_Alias.php
src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Swagger2.php
src/Classes/ServiceAPI/MyRadio_Timeslot.php

Turns out there are a lot of errors/warnings in MyRadio that we never see. Putting a log statement at https://github.com/UniversityRadioYork/MyRadio/blob/master/src/Classes/MyRadioError.php#L63 revealed many things, including many many thousands of unknown offsets from Database::decodeArray whenever certain people tried to select a timeslot. Presumably there's some text in there that the regex doesn't like.
Instead of trying to work out what was wrong with the horrible regex string, I just finished replacing it with the array_to_json/json_decode combo
Also fixed a couple of other errors that I was seeing in the same output log. There are more, but this cleans up the bulk of them (i.e. the ones that timelord uses every 3 seconds ;) )

Fix several warnings and memory issues

---

src/Classes/ServiceAPI/MyRadio_User.php

There's still some irritating code duplication in setPayment itself, but that can be fixed later
The other usage of setPayment is in markPaid.php and requires no changes

Make setPayment update the user cache object when necessary

---

src/Classes/SIS/SIS_Utils.php

Because "YorkUnited Kingdom" isn't quite as good as "York, United Kingdom".

Add some space between city and country in SIS messages

---

src/Classes/iTones/iTones_Utils.php

Fixes the speed issue with the getTrackForJukebox API and requesting tracks.
Turns out that after #708, the line was missing for telnet commands to be sent, so we didn't get a response, causing a timeout.

Fixed Missing Telnet line for Jukebox API

---

src/PublicAPI/rtfm/index.html

This allows the RTFM swagger API documentation to follow the API it's installed in, instead of defaulting to the production one.

Make RFTM use the correct API json file.

---

src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Public/js/myradio.podcasts.js

getPreviousTimeslots is used by UniversityRadioYork/2016-site#82 to get the "You just missed" mixcloud shows. Needs work/advice to actually get more than one result back.
Changes to toDataSource allow 2016-site to have a direct file URI to the podcast files.
Todo: Make sure the podcast interface within myradio hides the extra fields. DONE
Goes with UniversityRadioYork/myradio-go#42

Add a couple of Podcast API features for 2016site

---

src/Classes/ServiceAPI/MyRadio_Track.php

Prevents the exception that probably causes uploads to disappear after cache resets.

Fix Uploader not knowing which user uploaded.

---

src/Classes/ServiceAPI/MyRadio_APIKey.php
src/Classes/ServiceAPI/MyRadio_TrainingStatus.php

When fetching permissions, always cast the IDs to integers. PHP doesn't particularly care, because why typing? However, this means that API calls such as /user/7449/permissions return a mixture of integer and strings-with-numbers-in, which can be Confusing.

Always use integers for permissions

---

src/Public/css/sis.css

Everywhere else (including other full width pages in MyRadio - Show Planner etc.) has the nav not full width. Makes SIS match.

Fix inconsistent nav width in SIS

---

src/Classes/ServiceAPI/MyRadio_TracklistItem.php

This fixes the fact that if a manual tracklist is made, the album appears as a plain text string in the API.
This is different from the full MyRadio_Album object for regular tracks.
Fixes UniversityRadioYork/2016-site#102 UniversityRadioYork/2016-site#46

Manual Tracklist Album Consistancies

---

src/Classes/MyRadio/MyRadioFormField.php
src/Classes/ServiceAPI/MyRadio_User.php

Fixes ***Warning : strip_tags() expects parameter 1 to be string, array given - In /usr/local/www/myradio/src/Classes/MyRadio/MyRadioFormField.php on line 612*** errors.

Fix Bulk Add by fixing Text/Email fields in Tabularsets.

---

src/Menus/menu.json

This is a major change to the site functionality and may take several hours to review... 
- The description of Book Off-Air studio contained a reference to studio 2.

Removed reference to studio 2

---

scripts/bootstrap.sh
src/Classes/MyRadio/CoreUtils.php
src/Classes/MyRadio/MyRadioForm.php
src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Controllers/Podcast/editPodcast.php
src/Controllers/Scheduler/editSeason.php
src/Controllers/Scheduler/editShow.php

Fixes #582
Fixes #751
2016-site has already implemented shortening via page overflow, but this forces each tag to be 24 chars or less (picked by @Danzibob to be nice looking).

Limit the length of tags and comma delimit.

---

src/Classes/ServiceAPI/MyRadio_Podcast.php

Podcasts always included suspended rows and so broke the website, now it has a parameter.
Changes also made to myradio_go and 2016_site in accordance with this.

Added includeSuspended parameter to getAll endpoint

---

src/Classes/NIPSWeb/NIPSWeb_ManagedItem.php
src/Public/css/planner.css
src/Public/js/nipsweb.import.js
src/Templates/NIPSWeb/import.twig

Something that should have been there from the start (this has caused lots of people to play old jingles etc on shows because they continuously imported them from show to show).
Tested (and still running) on myradio-dev.

Prevent Importing expired/undigitised items into show plans.

---

src/Classes/ServiceAPI/MyRadio_Show.php

Somehow this state occurs where the incorrect show image URL including the server path gets cached. Clearing the cache would fix it as the show was _construct()'ed again.

Fix show image caching bug.

---

src/Classes/ServiceAPI/MyRadio_Webcam.php
src/Controllers/Webcam/a-trackViewer.php
src/Public/js/myradio.webcam.tracker.js

No longer will we get a wall of HTML over email every time someone leaves the webcams page open and clicks "Report" on the Error popup model. Also was caused by having multiple webcam pages open.

Prevent broken email when browser wakes.

---

src/Classes/SIS/SIS_Utils.php

No reasonable human is going to send more than a tweet's length anyway

Limit SIS message length to 1k chars and fix logic error

---

src/Classes/ServiceAPI/MyRadio_Podcast.php

- clarify that image sizes should be 400x400px
- ask to notify Comp about cache breakage
Context (URY members only): https://ury.slack.com/archives/C091ZRR63/p1572298733002700

Update messaging on podcast form fields

---

scripts/migrate-show-colours.php
src/Classes/MyRadio/CoreUtils.php
src/Classes/ServiceAPI/MyRadio_Creditable.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Classes/ServiceAPI/MyRadio_ShowSubtype.php
src/Controllers/Scheduler/editSeason.php
src/Controllers/Scheduler/editShow.php

Hoo boy is this a crazy PR.
This is a big project, comprised of several PRs. See [here](https://github.com/orgs/UniversityRadioYork/teams/officers/discussions/1) for the plan (internal only). This PR is a continuation of https://github.com/UniversityRadioYork/2016-site/pull/212
In this PR, we finish the job by adding editing forms for subtypes in MyRadio.
As part of this, I also discovered that the season editing form is hopelessly broken. Some of the later commits in this series are me trying to unbreak it, fruitlessly. I might have another pop at it. Oh well, the show-level subtype logic works and is tested on dev.
Test Plan:
* Deploy to dev
* Check that creating a show works fine, including the subtype (i.e. it's returned in the API)
* Ditto for editing shows
* Check for applying a new …

Moving show subtypes into MyRadio, part 6 - FINISH HIM

---

src/Templates/Profile/user.twig

YUSU backpages is dead (rip) and people get confused by "paid: £0.00"

Hide payments on profile pages

---

src/Classes/iTones/iTones_Utils.php

This PR makes getTrackToPlay more reliable by properly checking if the potential track is currently being played. Previously it only checked if it was in a queue (plus some half-baked attempt to check the current queue that I don't think ever worked).
This is based on this change to Jukebox: UniversityRadioYork/jukebox@54fffed

Make jukebox getTrackToPlay more reliable

---

src/Classes/ServiceAPI/MyRadio_User.php

Make sure that if the user sends email via their eduroam email, that email the server (via myradio/alias-go) will accept that user as valid.

Allow Uni MTA to accept emails from eduroam users.

---

src/Public/js/nipsweb.player.js

If a save fails, showplanner stops saving changes, but still lets users drag tracks around, which could potentially lead to them making changes that aren't saved. To ensure this doesn't happen, disable showplanner prior to reloading.

Lock the showplanner if saving fails

---

schema/data-auth.json
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Classes/ServiceAPI/MyRadio_TracklistItem.php
src/Public/js/myradio.stats.fulltracklist.js

Allows users (with new permissions) to tracklist for shows using WebStudio.
Also allows WebStudio to get the current logged in user/selected timeslot data.

Add WebStudio API User Session and Tracklisting

---

schema/data-actions.json
schema/data-actionsauth.json
schema/data-auth.json
src/Controllers/MyRadio/webstudio.php
src/Menus/menu.json

This PR adds an action to direct users to WebStudio.
I've already created an associated "WebStudio Trained" presenterstatus on prod, verified correct operation on Staging.

Add WebStudio action and associated permissions

---

src/Controllers/email_pipe.php

If a message is spam, Exim doesn't set the `X-Spam-Status: yes` header, but rather the `X-Spam_action: reject` header. Update the email_pipe controller to use the correct one.

email_pipe: use the proper spam status header

---

src/Classes/ServiceAPI/MyRadio_Podcast.php

That's what most of the big players use (tested Serial and Relay FM), and frankly 192k is overkill for an hour of speech anyway

Reduce podcast bitrate to 128kbps

---

src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Controllers/Podcast/allPodcast.php

Reverted this, as it broke the prod site.
```
/tank/jenkins/workspace/2016-site/go/src/github.com/UniversityRadioYork/2016-site/controllers/index.go:42: /podcast/allpodcasts Not ok: HTTP 500
{"status":"FAIL","payload":"Query failure: SELECT podcast_id FROM uryplayer.podcast WHERE suspended = false AND submitted IS NOT NULLORDER BY submitted DESC OFFSET 0 LIMIT 10;<br>Params: array (\n)<br>ERROR:  syntax error at or near \"NULLORDER\"\nLINE 1: ...cast WHERE suspended = false AND submitted IS NOT NULLORDER ...\n                                                             ^\n","time":"0.028428"}
[negroni] 2020-05-18T16:31:47+01:00 | 0 |        245.64841ms | localhost:5612 | GET /
```

Revert "Add include_pending to allpodcasts API, so website can ignore them."

---

src/Classes/MyRadio/MyRadioSession.php

Seems to be triggered a fair bit by timelord spamming the API on load, one request creates a session just before another is half-way through doing the same, leading to an insertion conflict.
Could we actually get rid of the SELECT and just return the values from the INSERT?

Fix SSO 500 Race Condition

---

schema/data-auth.json
src/Classes/ServiceAPI/MyRadio_Timeslot.php

This needs to be followed up with a DB change to add in the new permission and give (all? most?) users access to MyRadio_Timeslot::getMessages - it'll take care of authorization

Add auth to SIS messages API endpoint

---

src/Classes/ServiceAPI/MyRadio_User.php

The current User API only includes non-membership officerships (so e.g. computing officerships are excluded). Add a way to get at those without doing cursed things.

Add MyRadio_User::toDataSource "all_officerships" mixin

---

src/Classes/ServiceAPI/MyRadio_User.php

Reverts UniversityRadioYork/MyRadio#913.
It appears to pollute the cache - after sending an `all_officerships` request, it'll be returned even if an `officerships` request is sent later.

Revert "Add MyRadio_User::toDataSource "all_officerships" mixin"

---

src/Classes/ServiceAPI/MyRadio_User.php
src/Classes/ServiceAPI/ServiceAPI.php

The current User API only includes non-membership officerships (so e.g. computing officerships are excluded). Add a way to get at those without doing cursed things.
This time with working caching (or lack thereof).

Add MyRadio_User::toDataSource "all_officerships" mixin, take two

---

schema/api.graphql
src/Classes/ServiceAPI/MyRadio_Officer.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Classes/ServiceAPI/MyRadio_UserOfficership.php

This changes it from returning a hacky array to a new class, MyRadio_UserOfficership, and updates all call sites to match. The primary benefit is a much cleaner GraphQL API - instead of just getting an "officerid", all officership info can be traversed directly from the User object

Refactor MyRadio_User::getOfficerships

---

schema/data-auth.json
src/Classes/ServiceAPI/MyRadio_TrainingStatus.php

As part of the Great 2020 Training Reshuffle, we're adding the first training status that has multiple prerequisites. Now, I'm a lazy bastard who can't be bothered to write the code for that, so instead I'll just make that perm have no prerequisites, and instead give whoever can give it the ability to give anything ;)
This will need to be followed up with a SQL change:
```sql
INSERT INTO public.l_action (descr, phpconstant) VALUES ('Give Anyone Any Training Status', 'AUTH_AWARDANYTRAINING');
```

Add permission to let someone train anyone in anything

---

src/Classes/ServiceAPI/MyRadio_TracklistItem.php

Not tested yet, but should fix single timeslot credits from not being able to tracklist.

Use credits for the timeslot, not whole show.

---

src/Classes/ServiceAPI/MyRadio_Creditable.php
src/Classes/ServiceAPI/MyRadio_Scheduler.php

This allows co-presenters (and others, as specified in the credits db table) to appear in the presenters string used by radioplayer etc. Replaces #800.

Use is_in_byline to generate presenter string.

---

.gitignore
src/Classes/ServiceAPI/MyRadio_MetadataSubject.php

Currently, https://ury.org.uk/api/v2/show/searchmeta/a is a one-way ticket to DoS city.
I would like to switch this to use Postgres' built-in FTS, but the metadata system makes this a bit tricky.
h/t @cs-499243 for pointing this out

Limit the number of search results returned

---

src/Classes/ServiceAPI/MyRadio_MetadataSubject.php

https://ury.org.uk/search/?term=mixer has the same show five? times.

Use SELECT DISTINCT to avoid returning the same search result multiple times

---

src/Classes/ServiceAPI/MyRadio_Timeslot.php

To ensure that non-WS-Trained people can still access it.
**Note:** I reused AUTH_USENIPSWEB to avoid creating _yet another_ permission - so, when this is merged, we'll need to change auth for MyRadio_Timeslot::getShowPlan to NULL, and also reduce the number of people with AUTH_USENIPSWEB. In fact, now that I write this, might it be better to just add a new one, or rename AUTH_USENIPSWEB?

Add AUTH_USENIPSWEB check to MyrTimeslot::getShowPlan

---

src/Classes/ServiceAPI/MyRadio_Timeslot.php

Don’t *think* this is a breaking change? Just more semantically correct.

MyRadio_Timeslot: throw 404 not 400 if it doesn’t exist

---

src/Templates/MyRadio/menu.twig

Makes it so only clicking on non MyRadio links will open in new tabs, any internal link will use the same tab

Only new tabs for external links

---

src/Menus/menu.json

Change "decription" to "description" so the minutes description actually works

Spell description correctly

---

schema/base.sql
schema/patches/9.sql
src/Classes/ServiceAPI/MyRadio_Selector.php
src/Classes/ServiceAPI/MyRadio_TracklistItem.php

This is to allow support via API for BAPS3 to tracklist always, but only show in tracklists if the studio is on air.
Instead of using the server name mapping in BAPS2, this proposes to create 3 tracklist source chars (studio red, blue and OB), configured on each server.
Note, the table will need to be created (if I haven't done it already) in prod db, and all source mapping combos added (including webstudio to sel 5, etc).
Needs testing.

Add mapping of tracklist sources to sel sources

---

src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/ServiceAPI.php

The following paragraph about summarises the cursedness of this issue:
```php
// Pre-emptively write the current state of this object to the cache.
// We need to do this, because the self::getInstance() call above
// poisoned the cache with a NULL $podcast->metadata. So anything
// that tries to read it from now on will hit the cache and get
// an outdated copy. The only remedy is to, effectively, re-poison it
// with the correct value. Yes, this is absolutely cursed.
//
// This is, however, safe: nothing should be able to know the podcast's
// ID until the COMMIT statement afterwards. So by the time it
// has an ID, it will have a freshly baked, correct value waiting
// for it in the cache.
//
// This is not a unique problem; in theory, every ServiceAPI subclass
// is vulnerable.
//
// …
```

Attempt to fix podcast caching, yet again

---

src/Classes/ServiceAPI/MyRadio_Podcast.php
src/Classes/ServiceAPI/MyRadio_Swagger2.php

There's an obscure case in the API code where api_key and mixins could leak into a method's arguments when they really never should. This PR fixes that case, and also un-reverts #1015 (which was blocked due to this).
This doesn't fix the general case though - try calling https://ury.org.uk/api-staging/v2/show/14066/credits?unexpected=gobbledygok - if a method that takes one parameter is called with one parameter, no validation is done to ensure that it's actually called with the expected parameter.
I'm not sure how best to fix that, honestly - the comment on https://github.com/UniversityRadioYork/MyRadio/blob/master/src/PublicAPI/index.php#L59 refers to the case where "the request body is the param", and I'm not quite sure what that means. Perhaps we just accept this as a fact of life, …

Quick fix for methods that take only one parameter breaking (un-revert #1019)

---

src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/Profile/bulkAdd.php
src/Controllers/Profile/quickAdd.php

Every year we have the problem of people getting confused when they sign up and don't get an email, because they already had an account.
This commit changes MyRadio_User::createOrActivateUser() to return null when the user already existed before it was called.
This is a BREAKING CHANGE because, although all MyRadio callsites have been updated, various places use its API and would need updating too (off the top of my head, /getinvolved and the alumni signup form).
This also technically introduces an account enumeration vulnerability, but personally I think the UX benefit is worth the marginal added risk.

BREAKING CHANGE: createOrActivate return null when user exists

---

README.md
Vagrantfile
schema/base.sql
scripts/bootstrap.sh
scripts/reset-db-preSetup.sh
src/Controllers/Setup/dbschema.php
src/Controllers/root.php

- Do basic version updates for postgres and php
- Remove oids from base.sql - Closes #1037 
- Create basic bash script to wipe database cleanly (so you can edit the setup scripts without rerunning `vagrant up` each time)
- Set MYRADIO_CURRENT_SCHEMA_VERSION to the latest patch version (which I think we were meant to have been doing, since that's how it sees whether to install patches)
- Create a loop in dbschema because it has an issue where it applies base.sql but then, on the next query, doesn't seem to be able to find its changes in the database. This makes it repeat maybe 3 times but limits the amount a user has to do to get it working (which is a fair compromise)
- Other minor edits to dbschema to avoid weird unexpected cases

Fix local install process

---

schema/patches/12.sql
src/Classes/ServiceAPI/MyRadio_Demo.php
src/Controllers/Training/createDemo.php
src/Controllers/Training/leaveDemo.php
src/Controllers/Training/listDemos.php
src/Controllers/root.php

Make the cutoff configurable, so that people can set it accordingly - early morning sessions may want notice, while people who are going to be at the station anyway don'ŧ really mind.
Screenshots in action (on my local dev environment):
Also merged with @hicks927's work on setting an attendee limit, because it makes sense to do them at the same time:

Training cut-off + people limit (fixes #1049, fixes #1052)

---

src/Classes/ServiceAPI/MyRadio_Demo.php

`demo_time` is a string, not an int.

Fix failure to signup when a signup cutoff is set

---

schema/patches/15.sql
src/Classes/ServiceAPI/MyRadio_TrainingStatus.php
src/Classes/ServiceAPI/MyRadio_UserTrainingStatus.php
src/Controllers/root.php

An archived training status can still be seen for anyone who already has it, but can't be newly given.
Tested locally in Docker.

Allow archiving a training status

---

src/Classes/ServiceAPI/MyRadio_Swagger2.php

because of `setUserSelectedTimeslot` being static (because it sets it in the session), it considers it the GET method.
By pure chance in the last 2.5 years, when going through the methods, it looked at setUST first, said it was the get method, then saw getUST and overwrote that as the GET method, but now it's seeing them in the other order, so overwrites getUST with setUST as the GET method. Because there's no ordering to the methods [I assume], just the order they happen to be returned in, and we've been relying on getUST coming second.
I put it in as an edge case cause it kinda is - static method setting a thing essentially 'globally'

fix userSelectedTimeslot

---

src/Classes/MyRadio/MyRadioDefaultAuthenticator.php

Removed the html hyperlink tag to make the reset link appear in plain text so that people can still reset their passwords while comp team fix the email formatting problem

Temp fix to password reset email in MyRadioDefaultAuthenticator.php

---

schema/data-actions.json
schema/data-actionsauth.json
schema/patches/18.sql
scripts/gdprdeleteall.php
scripts/gdprdeleteuser.php
scripts/gdpremail.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/MyRadio/login.php
src/Controllers/MyRadio/privacystatement.php
src/Controllers/Profile/edit.php
src/Templates/MyRadio/privacy.twig

three main features:
-A mandatory privacy policy that users must accept on their first attempt to login
-the ability to opt into and out of account deletion
-php scripts for emailing users eligible for deletion and for deleting users

GDPR compliance

---

Dockerfile
build.xml
composer.json
schema/patches/18.sql
schema/patches/19.sql
src/Classes/Database.php
src/Classes/MyRadio/AuthUtils.php
src/Controllers/Setup/dbdata.php
src/Controllers/root.php

Two changes in this PR:
* First upgrades the Dockerfile to PHP 8.2. I had to remove a bunch of dev-only Composer dependencies that don't support PHP 8 (and some don't exist at all anymore) - the only risky one is codeception which is a major version bump 
* Second onwards is all the changes I had to make to the setup flow to get it to succeed in one go - mainly making all the database operations idempotent and a few other smaller fixes.

Upgrade development Dockerfile to PHP 8 + setup fixes

---

Dockerfile
Dockerfile.prod
build.xml
composer.json
schema/patches/18.sql
src/Classes/Config.php
src/Classes/Database.php
src/Classes/MyRadio/AuthUtils.php
src/Classes/ServiceAPI/MyRadio_Demo.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Controllers/MyRadio/jwt.php
src/Controllers/Setup/dbdata.php
src/Controllers/root.php
src/Menus/menu.json
src/MyRadio_Config.local.php.dist
src/Public/js/myradio.training.demolist.js

few things:
- few updates for running in the container after thunderhorn said "no more myradio for you"
- updates for the off air studio booking app, such as myradio issuing jwts to do better authentication than what we had
Then, we can have what's running be up to date with github again, and can then give it to jenkins now the new version is running _mostly_ ok.

fun fact: this has been running in prod for a while

---

docs/install.md
schema/api.graphql
schema/api.json
schema/base.sql
schema/patches/19.sql
scripts/gdprdeleteuser.php
src/Classes/MyRadio/MyRadioNews.php
src/Classes/ServiceAPI/MyRadio_Season.php
src/Classes/ServiceAPI/MyRadio_Timeslot.php
src/Classes/ServiceAPI/MyRadio_Track.php
src/Classes/ServiceAPI/MyRadio_User.php
src/Classes/ServiceAPI/Profile.php
src/Controllers/Profile/bulkAdd.php
src/Controllers/Profile/edit.php
src/Controllers/Profile/quickAdd.php
src/Controllers/Setup/user.php
src/Controllers/root.php
src/Public/js/myradio.form.js
src/Public/js/myradio.timeslot.js
src/Templates/Profile/user.twig
src/Templates/Setup/user.twig
tests/api/ShowSpecCest.php

Additions:
Nicknames - called nnames
- Database new column character varying 255 (can be null) member.nname
- 19.sql patch to allow for upgrades (manual migration must be done)
- (this has already been completed on ury's version of myradio)
Rewording:
- In my investigations of trying to fix 2016 site and myradio connections. I stumbled upon a miscommunication that user profiles have the email listed as public obtainable. But isn't called that in the user profile editor.
-Other minor updates
adds comments on what to remove if you want to setup your own mini ury (this is needed as 2016 site expects a mixcloud item)
Thank you for reading this pr,
(sorry whoever has to review it)
Also sorry for the scuffed ness I am on a train
Ren
See pictures below of example changes as tested on my docker …

Adding Nickname's to users and fixing some wordings on user profile to be line with gdpr

---

src/Menus/menu.json

I added a section called Tools + Merch because I didn't know what section the latter went in. I'm free to change it.

Split the I want to section

---

src/Classes/ServiceAPI/MyRadio_Event.php
src/Controllers/Events/editEvent.php

fun fact: myradio only makes me want to scream 99% of the time

events can have a different owner

---

src/Classes/Config.php
src/Templates/Training/createDemo.twig

Replaces the schedule preview with the booking form from the booking microservice site. This URL is set in the `config.php`.
Resolves issue with https://github.com/orgs/UniversityRadioYork/projects/10/views/6?pane=issue&itemId=80365237&issue=UniversityRadioYork%7CMyRadio%7C1185  but does not close ticket

Show booking availability in training form

---

src/Classes/ServiceAPI/MyRadio_Podcast.php

iTunes has changed its requirements for uploading podcast images from RSS feeds. Docs offer a range of options but request largest size which is 3000x3000
> Size: Square; 3000 x 3000 pixels. If you’re submitting your show via RSS feed, Apple Podcasts accepts show cover artwork ranging from 1400 x 1400 to 3000 x 3000 pixels. The largest size is preferred.
[https://podcasters.apple.com/support/896-artwork-requirements#:~:text=Size%3A%20Square%3B%203000%20x%203000,to%203000%20x%203000%20pixels.](https://podcasters.apple.com/support/896-artwork-requirements#:~:text=Size%3A%20Square%3B%203000%20x%203000,to%203000%20x%203000%20pixels.)

Update podcast art size requirements

---

src/Menus/menu.json

`Config:: $contract_uri` must also be updated in the config file to reflect the new link `https://drive.google.com/drive/folders/1njt5quPCok7Jkab9lyKTSZnwJ4tXnq99?usp=sharing`

Link to new presenters' contract in google drive

---

src/Classes/MyRadioError.php
src/Classes/ServiceAPI/MyRadio_Show.php
src/Classes/ServiceAPI/MyRadio_User.php

I am going to spend a couple of weeks fixing (or at least noting down) PHP warnings at the top of myradio pages, then i'll undraft this

fix: several warnings from php8 migration

---

src/Menus/Scheduler.json

Includes a link to the new scheduler microservice [Baraddur](https://github.com/UniversityRadioYork/BaradDur/)

Add link to baraddur to scheduler page
